collision_world:
    size_x: 3.5
    size_y: 3.0
    size_z: 2.5
    origin_x: -1.0
    origin_y: -1.5
    origin_z: -1.25
    res_m: 0.02
    max_distance: 0.2

collision_groups:
  - name: manipulator
    type: spheres
    root_name: base_link
    tip_name: ee_link
    collision_links:
    - name: shoulder_link
      root: shoulder_link
      spheres: sh0 sh1 sh2
    - name: upper_arm_link
      root: upper_arm_link
      spheres: ua0 ua1 ua2 ua3 ua4 ua5 ua6 ua7 ua8
    - name: forearm_link
      root: forearm_link
      spheres: fa0 fa1 fa2 fa3 fa4 fa5
    - name: wrist_1_link
      root: wrist_1_link
      spheres: gr0 gr1 gr2
    - name: wrist_2_link
      root: wrist_2_link
      spheres: lf0 lf1
    - name: wrist_3_link
      root: wrist_3_link
      spheres: rf0 rf1
    - name: ee_link
      root: ee_link
      spheres: rft0 rft1

collision_spheres:

  - { name: sh0, x: 0.00, y: 0.00, z: 0.00, radius: 0.08, priority: 5 }
  - { name: sh1, x: 0.00, y: 0.07, z: 0.00, radius: 0.08, priority: 5 }
  - { name: sh2, x: 0.00, y: 0.14, z: 0.00, radius: 0.08, priority: 5 }

  - { name: ua0, x: 0.0,    z: 0.000,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: ua1, x: 0.0,    z: 0.066,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: ua2, x: 0.0,    z: 0.133,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: ua3, x: 0.0,    z: 0.200,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: ua4, x: 0.0,    z: 0.266,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: ua5, x: 0.0,    z: 0.333,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: ua6, x: 0.0,    z: 0.400,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: ua7, x: 0.0,    z: 0.400,   y: -0.07,   radius: 0.08,   priority: 2 }
  - { name: ua8, x: 0.0,    z: 0.400,   y: -0.14,   radius: 0.08,   priority: 2 }

  - { name: fa0, x: 0.0,    z: 0.066,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: fa1, x: 0.0,    z: 0.133,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: fa2, x: 0.0,    z: 0.200,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: fa3, x: 0.0,    z: 0.266,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: fa4, x: 0.0,    z: 0.333,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: fa5, x: 0.0,    z: 0.400,   y:  0.00,   radius: 0.08,   priority: 2 }

  - { name: gr0, x: 0.0725, y: -0.0175, z: 0.00, radius: 0.04, priority: 2 }
  - { name: gr1, x: 0.0725, y: 0.0175,  z: 0.00, radius: 0.04, priority: 2 }
  - { name: gr2, x: 0.0925, y: 0.0,     z: 0.00, radius: 0.04, priority: 2 }

  - { name: lf0, x: 0.03, y: 0.025,     z: 0.00, radius: 0.04,  priority: 1 }
  - { name: lf1, x: 0.08, y: 0.0175,    z: 0.00, radius: 0.035, priority: 1 }

  - { name: rf0, x: 0.03, y: -0.025,    z: 0.00, radius: 0.04,  priority: 1 }
  - { name: rf1, x: 0.08, y: -0.0175,   z: 0.00, radius: 0.035, priority: 1 }

  - { name: rft0, x: 0.015, y: 0.005, z: 0.00, radius: 0.03, priority: 1 }
  - { name: rft1, x: 0.035, y: 0.005, z: 0.00, radius: 0.02, priority: 1 }

  - { name: lft0, x: 0.015, y: -0.005, z: 0.00, radius: 0.03, priority: 1 }
  - { name: lft1, x: 0.035, y: -0.005, z: 0.00, radius: 0.02, priority: 1 }
