collision_world:
    size_x: 3.5
    size_y: 3.0
    size_z: 2.5
    origin_x: -1.0
    origin_y: -1.5
    origin_z: -1.25
    res_m: 0.02
    max_distance: 0.2

collision_groups:
  - name: manipulator
    type: spheres
    root_name: base_link
    tip_name: ee_link
    collision_links:
    - name: shoulder_link
      root: shoulder_link
      spheres: sh0 sh1
    - name: upper_arm_link
      root: upper_arm_link
      spheres: ua0 ua1 ua2 ua3 ua4 #ua5
    - name: forearm_link
      root: forearm_link
      spheres: fa0 fa1 fa2 fa3 fa4 fa5
    - name: wrist_1_link
      root: wrist_1_link
      spheres: w10 w11
    - name: wrist_2_link
      root: wrist_2_link
      spheres: w20 w21
#    - name: wrist_3_link
#      root: wrist_3_link
#      spheres: rf0 rf1
#    - name: ee_link
#      root: ee_link
#      spheres:

collision_spheres:

  - { name: sh0, x: 0.00, y: 0.00, z: 0.00, radius: 0.08, priority: 5 }
  - { name: sh1, x: 0.00, y: 0.07, z: 0.00, radius: 0.08, priority: 5 }

  - { name: ua0, x: 0.0,    z: 0.0,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: ua1, x: 0.0,    z: 0.105,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: ua2, x: 0.0,    z: 0.21,   y:  0.00,   radius: 0.08,   priority: 4 }
  - { name: ua3, x: 0.0,    z: 0.315,   y:  0.00,   radius: 0.08,   priority: 2 }
  - { name: ua4, x: 0.0,    z: 0.42,   y:  0.00,   radius: 0.08,   priority: 2 }

  - { name: fa0, x: 0.0,    z: 0.0,   y:  0.00,   radius: 0.06,   priority: 4 }
  - { name: fa1, x: 0.0,    z: 0.1,   y:  0.00,   radius: 0.06,   priority: 4 }
  - { name: fa2, x: 0.0,    z: 0.2,   y:  0.00,   radius: 0.06,   priority: 4 }
  - { name: fa3, x: 0.0,    z: 0.3,   y:  0.00,   radius: 0.06,   priority: 2 }
  - { name: fa4, x: 0.0,    z: 0.39,   y:  -0.019,   radius: 0.05,   priority: 2 }
  - { name: fa5, x: 0.0,    z: 0.39,   y:  0.019,   radius: 0.05,   priority: 2 }

  - { name: w10, x: 0.0, z: -0.018, y: 0.09, radius: 0.05, priority: 2 }
  - { name: w11, x: 0.0, z: 0.018,  y: 0.09, radius: 0.05, priority: 2 }

  - { name: w20, x: 0.0, z: 0.09,     y: -0.018, radius: 0.05,  priority: 1 }
  - { name: w21, x: 0.0, z: 0.09,    y: 0.018, radius: 0.05, priority: 1 }
