manipulator:
  planner_configs:
    arastar.bfs.manip:
      graph_config: ManipulatorManipLatticeConfig
      heuristic_config: BFSConfig
      search_config: ARAConfig
      shortcut_config: EuclideanConfig
    larastar.bfs.manip:
      graph_config: ManipulatorManipLatticeConfig
      heuristic_config: BFSConfig
      search_config: LARAConfig
      shortcut_config: EuclideanConfig
    egwastar.bfs_egraph.manip_egraph:
      graph_config: ManipulatorManipLatticeEgraphConfigDefault
      heuristic_config: BFSEGraphConfig
      search_config: EGWAConfigDefault
      shortcut_config: EuclideanConfig

search_configs:
  ARAConfig:
    search: arastar
    epsilon: 100.0
  MHAConfig:
    search: mhastar
    epsilon: 100.0
    mha_epsilon: 2.0
  LARAConfig:
    search: larastar
    epsilon: 100.0
  EGWAConfigDefault:
    search: egwastar
    epsilon: 100.0


heuristic_configs:
  BFSConfig:
    heuristic: bfs
    bfs_res_x: 0.015
    bfs_res_y: 0.015
    bfs_res_z: 0.015
    bfs_sphere_radius: 0.02
  BFSEGraphConfig:
    heuristic: bfs_egraph
    bfs_res_x: 0.015
    bfs_res_y: 0.015
    bfs_res_z: 0.015
    egraph_epsilon: 5.0
    bfs_sphere_radius: 0.02
  JointDistConfigDefault:
    heuristic: joint_distance

graph_configs:
  ManipulatorManipLatticeConfig:
    graph: manip
    discretization:
        elbow_joint:            0.017453292519943
        shoulder_lift_joint:    0.017453292519943
        shoulder_pan_joint:     0.017453292519943
        wrist_1_joint:          0.017453292519943
        wrist_2_joint:          0.017453292519943
        wrist_3_joint:          0.017453292519943
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: true
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.2
    short_dist_mprims_thresh: 0.4
  ManipulatorManipLatticeEgraphConfigDefault:
    graph: manip_lattice_egraph
    discretization:
        elbow_joint:            0.017453292519943
        shoulder_lift_joint:    0.017453292519943
        shoulder_pan_joint:     0.017453292519943
        wrist_1_joint:          0.017453292519943
        wrist_2_joint:          0.017453292519943
        wrist_3_joint:          0.017453292519943
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: true
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.2
    short_dist_mprims_thresh: 0.4
  # ManipulatorWorkspaceConfigDefault:
  #   graph: workspace
  #ManipulatorManipLatticeConfigDefault:
  #  graph: manip


shortcut_configs:
  EuclideanConfig:
    shortcutter: euclidean
    shortcut_path: true
    shortcut_type: joint_space
    interpolate_path: true
